group = fr.fidorial
version = 0.1.0-SNAPSHOT

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.tooling.parallel = true
org.gradle.isolated-projects = true

# Minecraft related constants
# https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/protocolVersions.json
# minecraftVersionName rules: pre -> Pre-Release, snapshot -> Snapshot, rc -> Release Candidate
minecraftVersion = 26.3-rc-2
minecraftVersionName = 26.3 Release Candidate 2
protocolVersion = 1073742161
dataVersion = 5021
