[versions]
netty = "4.2.16.Final"
gson = "2.14.0"
slf4j = "2.0.17"
logback = "1.6.3"
faststats = "0.27.2"
fastutil = "8.5.19"
adventure = "5.2.0"
guava = "33.6.0-jre"
brigadier = "1.3.11"
jetbrains-annotations = "26.0.2"
jspecify = "1.0.1"
jline = "4.4.0"
spotless = "8.10.2"
spotless-lib = "4.8.0"
classgraph = "4.8.180"
shadow = "9.5.1"
dfu = "10.0.21"
adventure-nbt-dfu = "0.1.2"
diffpatch = "2.1.0.43"
spark = "1.10.182-SNAPSHOT"
spark-api = "0.1-SNAPSHOT"
leafpile = "1.2.0"

[libraries]
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
netty-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
netty-kqueue = { module = "io.netty:netty-transport-native-kqueue", version.ref = "netty" }
netty-iouring = { module = "io.netty:netty-transport-native-io_uring", version.ref = "netty" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
faststats-core = { module = "dev.faststats.metrics:core", version.ref = "faststats" }
faststats-config = { module = "dev.faststats.metrics:config", version.ref = "faststats" }
adventure-bom = { module = "net.kyori:adventure-bom", version.ref = "adventure" }
adventure-api = { module = "net.kyori:adventure-api" }
adventure-key = { module = "net.kyori:adventure-key" }
adventure-nbt = { module = "net.kyori:adventure-nbt" }
adventure-nbt-dfu = { module = "io.papermc:adventurex-nbt-dfu", version.ref = "adventure-nbt-dfu" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain" }
adventure-text-serializer-ansi = { module = "net.kyori:adventure-text-serializer-ansi" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage" }
adventure-text-logger-slf4j = { module = "net.kyori:adventure-text-logger-slf4j" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jline-ffm = { module = "org.jline:jline-terminal-ffm", version.ref = "jline" }
jline-reader = { module = "org.jline:jline-reader", version.ref = "jline" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
spotless-lib = { module = "com.diffplug.spotless:spotless-lib", version.ref = "spotless-lib" }
spotless-lib-extra = { module = "com.diffplug.spotless:spotless-lib-extra", version.ref = "spotless-lib" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
dfu = { module = "com.mojang:datafixerupper", version.ref = "dfu" }
diffpatch = { module = "io.codechicken:DiffPatch", version.ref = "diffpatch" }
spark-common = { module = "me.lucko:spark-common", version.ref = "spark" }
spark-api = { module = "me.lucko:spark-api", version.ref = "spark-api" }
leafpile = { module = "ca.spottedleaf:leafpile", version.ref = "leafpile" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version = "2.2.0" }

[bundles]
adventure = [
    "adventure-api",
    "adventure-key",
    "adventure-nbt",
    "adventure-text-serializer-gson",
    "adventure-text-minimessage",
    "adventure-text-logger-slf4j"
]
